server:
  port: 8080
 
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/dept?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
     com.zkx.cn.* : debug

